### ISSUE TITLE
Utf8Error

### ISSUE THREAD

**Issue by bms-dwh** [pacman82/arrow-odbc-py#10]
Got the following error when extracting a table from an MS SQL Server Database:
 
thread '<unnamed>' panicked at 'ODBC column had been expected to return valid utf8, but did not.: Utf8Error { valid_up_to: 78, error_len: None }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-odbc-0.6.1/src/column_strategy/text.rs:95:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

The datatype from the column that produced the error is nvarchar(40). Strangely, it works when I convert the column to nvarchar(42). 

OS: Ubuntu 20.04
Driver: ODBC Driver 17 for SQL Server
Source: MS SQL Server 2019
Python Version: 3.9

**Comment by pacman82** [comment]
Hi @bms-dwh , sorry you had to experience this Bug. Thank you very much for taking the time to report it!

> Strangely, it works when I convert the column to nvarchar(42).

I wonder if some truncation happens (shouldn't) and the truncated value stops being a valid utf-8 codepoint. I know this might take time, but if you could find out which value causes the behaviour, so we would have a reproducing test, I would be thankful.

One more thing: Currently the codebase **assumes** the character set is UTF if running on a Linux System. This error message could show up, if that assumption is wrong though (i.e. the system local specifies some ASCII codepage encoding). This is not consistent with you reporting that the error vanishes if you change the data type however.

**Comment by pacman82** [comment]
For reference:

* Upstream code triggering the panic: <https://github.com/pacman82/arrow-odbc/blob/e3813acefa72b27c3fbd94568fe897412dd389db/src/column_strategy/text.rs#L95>
* A line of code written under the assumption that no text has a longer octet length (i.e. binary) representation in UTF-8 than UTF-16.

**Comment by bms-dwh** [comment]
Hi Markus

Thanks a lot for the response. The package is really great, and it supports more data types than turbodbc and is even faster. Great!

In SQL Server 2019 you are able to collate to UTF-8. I tried different UTF-8 collations and always got the same error.

I thought I will query the table with 1 batch and search for the row that causing the error as I encountered another issue as I sorted the table:

arrow_odbc.error.Error: ODBC emitted an error calling 'SQLExecDirectW':
State: 42000, Native error: 1033, Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.

I got this error even I tried to sort on a table. It is probably creating a subquery in the backend.

I will try to search for the value, but it could take some time as the table has 93M rows.

Best regards,
Dominik

**Comment by pacman82** [comment]
Thanks, for your efforts so far, but I think I should be able to reproduce the error on my own from here on. Next time window I have I will google for a 3 Byte Utf-8 and 2 Byte Utf-16 unicode code point those Utf-8 representation becomes invalid if truncated. If I am not mistaken any such character might yield me a reproducing test if I put it into a small enough NVARCHAR column. The bug itself is an easy fix and would be very consistent with the symptomatic you are describing.

I'll keep you in the loop, once I deployed the bugfix, but first I must sleep.

Cheers, Markus

**Comment by bms-dwh** [comment]
Thanks a lot.
Just wanted to add that the ORDER BY Error was on my site, as I did a count over a subquery in my code.

Have a nice day.
Dominik

**Comment by pacman82** [comment]
Hi Dominik,

Issue is reproduced here: <https://github.com/pacman82/arrow-odbc-py/blob/e4ceceea4f6c5ae4fcdee9bd38fdb51bee35d08d/tests/test_arrow_odbc.py#L206>

The new version 0.1.11 including the upstream fix has been released. Please let me know if it also fixes the issue for you.

Cheers, Markus

**Comment by bms-dwh** [comment]
Hi Markus

It works like a charm.

Keep up the great work

Best regards,
Dominik
