### ISSUE TITLE
Use less restrict version specifier for `typing_extensions`

### ISSUE THREAD

**Issue by CDavantzis** [pacman82/arrow-odbc-py#108]
Right now typing_extensions is pinned to `4.12.0`. Users are blocked from upgrading to `4.12.2`, the current latest version.

You likely want to configure version specifier as `~= 4.12` instead of `== 4.12`.

https://pypi.org/project/typing-extensions/

> typing_extensions uses Semantic Versioning. The major version will be incremented only for backwards-incompatible changes. Therefore, it's safe to depend on typing_extensions like this: typing_extensions >=x.y, <(x+1), where x.y is the first version that includes all features you need.

https://packaging.python.org/en/latest/specifications/version-specifiers/

**Comment by pacman82** [comment]
You are right. My mistake, thank you. The latest release, actually might not even use them anymore.

**Comment by pacman82** [comment]
`arrow-odbc 8.0.1` is released, which does no longer depend on typing extensions for now. Thanks for raising this to my attention.
