### ISSUE TITLE
Unable to compile application using arrow-odbc.py

### ISSUE THREAD

**Issue by farooq-omer1** [pacman82/arrow-odbc-py#111]
I am having trouble in compiling python application on Windows OS which is using polars and arrow-odbc. I have tried to use both nuitka and pyinstaller but always received error: 

module arrow_odbc.arrow_odbc>
OSError: cannot load library 'F:\vm_share\GL_Bus_Tagging_RN11410_v3\RN11410_Process_Data.dist\arrow_odbc\arrow_odbc\arrow_odbc.so': error 0x7e

Can you please share guideline/method to compile the application.

**Comment by pacman82** [comment]
May I ask why you compile the arrow-odbc? It also ships complete with binaries as a windows wheel in pypi. See: <https://pypi.org/project/arrow-odbc/#files>

**Comment by farooq-omer1** [comment]
I am compiling my python app in which I have referenced arrow-odbc library. The application runs fine in conda environment. But, when I am compiled it to an exe file it failed to run and show me the error message which I shared.
I need your help and guidance to resolve this issue.
Thanks & regards

**Comment by pacman82** [comment]
Just to give you a bit of intermediate feedback. Definitely want to give you the option to compile against wide character set in non-windows platforms. Yet I still want to maintain the different defaults for windows and non-windows. I am currently looking into changes of the upstream `odbc-api` to facilitate this. Yet currently my open source time is spread thin.

**Comment by pacman82** [comment]
Building `arrow-odbc` with its Python is straight forward.

1. Install rust toolchain
2. Checkout arrow-odbc-py repository and make it the working directory 
3.

    ```shell
    python -m pip install build
    python build .
    ```
    
    
The trouble here is. You do not have an issue with building `arrow-odbc-py`. It seems to me you have trouble linking your own application. Somehow the linker does not find the dynamic library `arrow-odbc.so`.

I do not know how either `nuitka` or `pyinstaller` work. It seems to me though, you do not build the `arrow-odbc.so`. You need to enable your tooling to find it, and likely ship it with your application.

Best, Markus

**Comment by pacman82** [comment]
Just stumbled over this by accident. Likely not relevant anymore, but a py-installer hook has been provided since. See: https://github.com/pacman82/arrow-odbc-py/issues/197
