### ISSUE TITLE
Memory requirements for PostgresSQL

### ISSUE THREAD

**Issue by tomsej** [pacman82/arrow-odbc-py#24]
Thank you for this awesome library! I have been testing it for smaller tables Postgres tables ~1.5GB and everything worked pretty well and fast. But I tried to make it work with some bigger table and it is always killed with OOM killer:

**System:** Docker image with allocated 10GB RAM. Debian GNU/Linux 11 (bullseye). Python 3.9.13.
**Arrow ODBC version**: 0.2.0
**ODBC Driver:** PostgreSQL Unicode (from odbc-postgresql)
**Table size:** ~6.8GB

I have run the following code:

```
from arrow_odbc import read_arrow_batches_from_odbc

connection_string = "Driver={PostgreSQL Unicode};Server=xxxxx;Port=5432;Database=xxxx;"

reader = read_arrow_batches_from_odbc(
    query=f"SELECT * FROM xxx",
    connection_string=connection_string,
    batch_size=10,
    max_binary_size=1000,
    max_text_size=1000,
    user="xxxx",
    password="xxxx",
    falliable_allocations=False,
)

i = 1
for batch in reader:
    print(i)
    i += 1
```

When I run it the memory usage is constantly growing until the OOM killer kills the process. I have also tried to play with different values in `falliable_allocations `, `batch_size`, `max_binary_size`, and `max_text_size`, but nothing made a script finish. I would appreciate any hint.

Thanks a lot for your work!

**Comment by pacman82** [comment]
Hello @tomsej ,

thank you for the kind words. I am sad you are experiencing OOM issues. The whole point of batching is of course to keep only one batch in memory, so it can work with arbitrary large payloads.

Right now I can not spend time on this (maybe this weekend). Yet I can list three possible causes:

1. I screwed up and this package has a BUG
2. The Postgres ODBC driver keeps the entire result set in memory, independent of batching. Some DBs do this. I remeber at least earlier version of MySQL exhibiting this kind behaviour.
3. Python Garbage collection does not collect the batches, and so they just remain in memory.

There may be other possibilities, but to my mind it currently see that it must be at least one of these three things. If you feel like helping me to investigate, we could:

* Run the same query with `odbc2parquet` command line tool: <https://github.com/pacman82/odbc2parquet>
  Watch memory consumption. Running this tool takes Python out of the equation, but leaves the Postgres Database driver in.
* If Postgres seems innocent, does the behaviour change if we explicitly call garbage collection between iterations? Does it change if we explicitly delete the batches?

Looking forward to here from you again, and thanks for giving this library a spin!

Cheers, Markus

**Comment by tomsej** [comment]
Ok so I have:
- installed `odbc2parquet` into same docker container. I have run the following command:
```
odbc2parquet query --connection-string "Driver={PostgreSQL Unicode};Server=xxx;Port=5432;Database=candidate;UID=xxx;PWD=xxx;" out.par "SELECT * FROM xxx" --batch-size-memory 100Mb
```
I had the same problem. Memory is growing until killed by OOM killer.
- installed `turbodbc` and run same command with `fetchallarrow()`, also without success.

So I suppose the problem will be in Postgres ODBC driver. I will try different versions of that.

**Comment by pacman82** [comment]
Just googling a bit I found this nugget of wisdom:

> Something to keep in mind though, if the driver is *NOT* using the "Use
Declare/Fetch option", then the driver will attempt to store the entire query
results in its memory.  Is it possible your usage test would have done a huge
query or something like that?   The Use Declare/Fetch option only allocates a
cache of 100 rows (by default) and never goes over that so huge queries
wouldn't bother it.

See: <https://www.postgresql.org/message-id/37166E09.E02332D8%40insightdist.com>

Seems to me there is an option you could set then configuring the driver (maybe odbcinst.ini, or connection string ?) which would cause it to do well with large queries. It also gently hints, that `100` might then be the best batch size to use with postgresql odbc

**Comment by pacman82** [comment]
Stackoverflow to the rescue: <https://stackoverflow.com/questions/34009774/what-is-usedeclarefetch-postgresql-odbc>

Would recommend setting it higher than one, in case that option is **not** a bool though.

**Comment by pacman82** [comment]
> Use Declare/Fetch: If true, the driver automatically uses declare cursor/fetch to handle SELECT statements and keeps 100 rows in a cache. This is mostly a great advantage, especially if you are only interested in reading and not updating. It results in the driver not sucking down lots of memory to buffer the entire result set. If set to false, cursors will not be used and the driver will retrieve the entire result set. For very large tables, this is very inefficient and may use up all the Windows memory/resources. However, it may handle updates better since the tables are not kept open, as they are when using cursors. This was the style of the old podbc32 driver. However, the behavior of the memory allocation is much improved so even when not using cursors, performance should at least be better than the old podbc32.

Definetly set that to `true` i.e. `1`.

**Comment by pacman82** [comment]
@tomsej did it work?

**Comment by pacman82** [comment]
Hi @tomsej ,

having a strong suspicion that it can be solved by setting `UseDeclareFetch=1` for the Postgres Driver. I am closing this issue. Please reopen if this turns out to be wrong.

Cheers, Markus
