### ISSUE TITLE
Cannot set connection timeout

### ISSUE THREAD

**Issue by aersam** [pacman82/arrow-odbc-py#34]
Hi there!

I'm trying to use arrow-odbc to connect to an azure sql database which seems to have some timeout to connect. It would be great if I could set the connection timeout somehow, but that's not possible through connection string. I must be done by some ODBC Attribute according to the [MSFT Doc](https://learn.microsoft.com/en-us/dotnet/api/system.data.odbc.odbcconnection.connectiontimeout?view=dotnet-plat-ext-7.0#remarks) . Would it be possible to expose somehow an API that allows setting the Connection Timeout or more generic ODBC Attributes on calling `read_arrow_batches_from_odbc`?

**Comment by pacman82** [comment]
Hello @aersam ,

I think I could forward `SQL_ATTR_CONNECTION_TIIMEOUT` as described here: <https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetconnectattr-function>

The default for this timeout, is currently `0` meaning that no timeout is applied. I am not sure what your issue is currently. Is it that the default timeout by the Azure Database is to fast for you, or do you want to specify a quicker timeout yourself?

Asked differently: There are two timeouts. One after which the datasource gives up on the client, and one after the client gives up connecting the datasource. Within the application we can of course only control the client.

Best, Markus

**Comment by aersam** [comment]
Not sure we are on the same track... I want to use arrow-odbc-py and there I only pass the connection string to read_arrow_batches_from_odbc. How can I set this SQL_ATTR_CONNECTION_TIMEOUT  there? 

Also as far as I know the driver's default is 15s which is probably not enough for MS SQL Server, escpecially since I want to use Azure AD Auth.

My issue is that I cannot establish the odbc connection via arrow-odbc-py, but it does work with the same connection with pyodbc. The only difference is that I set there a relatively large timeout on doing  `pyodbc.connect` .

**Comment by pacman82** [comment]
> Not sure we are on the same track...

Sorry for causing confusion. Let's see if we can clear it up.

> . I want to use arrow-odbc-py and there I only pass the connection string to read_arrow_batches_from_odbc. How can I set this SQL_ATTR_CONNECTION_TIMEOUT there?

You currently can not. I just wanted to make sure it is the parameter you need, before I invest the work.

> My issue is that I cannot establish the odbc connection via arrow-odbc-py, but it does work with the same connection with pyodbc. The only difference is that I set there a relatively large timeout on doing `pyodbc.connect` .

This is helpful and clears it somewhat up for me. To help you understand why I was confused. By not specifying the timeout currently, we actually should (according to the standard) opt into no timeout at all, and wait as long as it takes. It seems though the driver does something different and an explicit timeout helps.

To implement this `odbc-api` needs updating, so `arrow-odbc` can be upgraded, so `arrow-odbc-py` can be upgraded. Still this might be happening fairly quick. Let's see.

Best, Markus

**Comment by pacman82** [comment]
I have to correct myself. The correct parameter to set is `SQL_ATTR_LOGIN_TIMEOUT `. The default is driver specific.

**Comment by pacman82** [comment]
Hello @aersam ,

`arrow-odbc-py 0.3.10` has been released featuring a `login_timeout_sec` parameter, which could solve your connection problem.

Cheers, Markus

**Comment by aersam** [comment]
Awesome! It's working!

Other question: Is there a command timeout in ODBC? Didn't hit one, so probably not...

**Comment by pacman82** [comment]
The only other timeout I see is `SQL_ATTR_CONNECTION_TIIMEOUT` which is not necessarily an upper limit of how long a command can take in total. Even so, its default is set to infinity.
