### ISSUE TITLE
Support : multiple result set

### ISSUE THREAD

**Issue by italanchan** [pacman82/arrow-odbc-py#35]
We have stored procedure like as:

create procedure simpleexample
@docno varchar(10)
as
begin
    Select * from dbo.documentheader where docno = @docno
    Select * from dbo.documentitems where docno = @docno
end

In fact, we have many similar stored procedures, e.g. invoice, salesorder, shiporder

Is there any sample code to support return multiple resultset from SP using arrow-odbc-py.

**Comment by pacman82** [comment]
Hello @italanchan ,

> Is there any sample code to support return multiple resultset from SP using `arrow-odbc-py`.

Currently there is no such code example, because arrow-odbc-py does not support multiple result sets. It makes sense to implement it, however my spare time is spread thin, so this might take a while.

Best, Markus

**Comment by pacman82** [comment]
`arrow-odbc-py 1.0.0` has just been released. It supports extracting multiple result sets, via the `more_results` method on the reader.

**Comment by pacman82** [comment]
```python
from arrow_odbc import read_arrow_batches_from_odbc

connection_string="Driver={ODBC Driver 17 for SQL Server};Server=localhost;"
reader = read_arrow_batches_from_odbc(
    query=f"SELECT * FROM MyTable; SELECT * FROM OtherTable;",
    connection_string=connection_string,
    batch_size=1000,
    user="SA",
    password="My@Test@Password",
)

# Process first result
for batch in reader:
    # Process arrow batches
    df = batch.to_pandas()
    # ...

reader.more_results()

# Process second result
for batch in reader:
    # Process arrow batches
    df = batch.to_pandas()
    # ...
```
