### ISSUE TITLE
Non-string paramaters cause an error.

### ISSUE THREAD

**Issue by rosscoleman** [pacman82/arrow-odbc-py#50]
I noticed that read_arrow_batches_from_odbc only supports string paramaters. There's some overhead if the database has to cast types when binding paramaters, so I think it would be best to support Python ints, floats, and dates.

I know the ODBC standard supports it:
https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/binding-parameter-markers?view=sql-server-ver16

If this is a lot of work, I think you should add a more descriptive error message that only string query parameters are allowed. I assumed there was a bug in how arrow-odbc was communicating with the database drivers for DB2 for IBM i, and I wasted time trying to figure that out. (Edit: until I actually looked at the source code for `to_bytes_and_len`)

If `query_params` is a list of integers in this code:
```
     reader = read_arrow_batches_from_odbc(
         query=query_sql,
         connection_string=job_config.dsn,
         batch_size=job_config.query_chunksize_small,
         parameters=query_params,
     )
```

I get this error:
```
INFO icmladds.db_util: Query with arrow-odbc
Traceback (most recent call last):
  File "/opt/queue/code/icmladds/main.py", line 43, in <module>
    main()
  File "/opt/queue/code/icmladds/main.py", line 29, in main
    load_feature_data.main()
  File "/opt/queue/code/icmladds/icmladds/batch/load_feature_data.py", line 606, in main
    store_demand_totals_curr = store_demand_totals(conn, curr_yr, curr_mo)
  File "/opt/queue/code/icmladds/icmladds/batch/load_feature_data.py", line 386, in store_demand_totals
    store_dmd_totals_curr_mo = db_util.query(
  File "/opt/queue/code/icmladds/icmladds/db_util.py", line 40, in query
    df = query_arrow_odbc(query_sql, query_params)
  File "/opt/queue/code/icmladds/icmladds/db_util.py", line 18, in query_arrow_odbc
    reader = read_arrow_batches_from_odbc(
  File "/opt/queue/code/icmladds/lib/python3.9/site-packages/arrow_odbc/reader.py", line 289, in read_arrow_batches_from_odbc
    encoded_parameters = [to_bytes_and_len(p) for p in parameters]
  File "/opt/queue/code/icmladds/lib/python3.9/site-packages/arrow_odbc/reader.py", line 289, in <listcomp>
    encoded_parameters = [to_bytes_and_len(p) for p in parameters]
  File "/opt/queue/code/icmladds/lib/python3.9/site-packages/arrow_odbc/connect.py", line 15, in to_bytes_and_len
    value_bytes = value.encode("utf-8")
AttributeError: 'int' object has no attribute 'encode'
```

**Comment by pacman82** [comment]
Hello @rosscoleman ,

> There's some overhead if the database has to cast types when binding paramaters, so I think it would be best to support Python ints, floats, and dates.

I am avoiding this as of now, as there is no clear mapping between Python and ODBC types. Should a `float` be converted to a `double` or a `Decimal`? Without inspecting the relational parameter type first, it is not possible to make a good decision in the genereal case. There is also not every conversion supported between ODBC types and Relational types on the database. String works everythere except for binary data.

> I think you should add a more descriptive error message that only string query parameters are allowed

Good idea. Please enjoy `arrow-odbc v1.2.4`. Which shoud provide a better error messae.

**Comment by rosscoleman** [comment]
When you are sending all paramaters as strings, is the database still binding paramaters? If you are instead concatenating strings to generate an SQL statement that includes paramater values, these methods would be vulneratble to SQL injection. If so, your API is really breaking my expectations about security. I've only ever used JDBC and pyodbc, and not ODBC from C or C++, but I wonder about this because JDBC drivers can throw errors if you send the wrong data types for bound parameters.

----

As for type conversions, I think pyodbc made sensible decisions. Definitely don't convert a python float to an SQL decimal, since one is base 2 and the other is base 10. I'm not sure why they picked SQL_NUMERIC instead of SQL_DECIMAL for python decimal.Decimal. Those two ODBC types look like aliases for the same type? 

https://github.com/mkleehammer/pyodbc/wiki/Data-Types

https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/sql-data-types?view=sql-server-ver16

**Comment by pacman82** [comment]
> When you are sending all paramaters as strings, is the database still binding paramaters? If you are instead concatenating strings to generate an SQL statement that includes paramater values, these methods would be vulneratble to SQL injection.

These are bound VARCHAR parameters. `arrow-odbc` does not perform string concatination and does not introduce vulnerability to SQL injection.

> Definitely don't convert a python float to an SQL decimal, since one is base 2 and the other is base 10.

SQL_DECIMAL is a relational type. It does not specify a representation. Multiple C-Types can be used to transfer SQL_DECIMAL.

>  I'm not sure why they picked SQL_NUMERIC instead of SQL_DECIMAL for python decimal.Decimal. Those two ODBC types look like aliases for the same type?

SQL_NUMERIC and SQL_DECIMAL differ in the range of values they support.

**Comment by pacman82** [comment]
I'll give your suggestions some thought. With my current workload it is hypothetical anyway. The better error message must suffice for now. Thanks for alerting me to the issue.
