### ISSUE TITLE
Increase default `max_bytes_per_batch`

### ISSUE THREAD

**Issue by jonashaag** [pacman82/arrow-odbc-py#71]
The current value is 2 MiB which IMO is very low. Can we safely assume that a typical user has at least 512 MiB to spare? So we could make batch size 256 MiB (to accommodate for double buffering). Probably 256 MiB is not Pareto optimal anymore, but how about 64 MiB? Turbodbc uses a default batch size of 20 MiB.

**Comment by pacman82** [comment]
🤦 Thanks for telling me. 256 is the intended default. Bugfix is released.

**Comment by jonashaag** [comment]
<3
