### ISSUE TITLE
turbodbc is faster at downloading

### ISSUE THREAD

**Issue by jonashaag** [pacman82/arrow-odbc-py#72]
In my benchmarks, it seems like Turbodbc with `use_async_io=True` is 20–30% faster than arrow-odbc-py with `fetch_concurrently()`.

I haven't done any profiling on this yet.

**Comment by jonashaag** [comment]
Btw, here https://github.com/pacman82/arrow-odbc-py/issues/47#issuecomment-1661655693 you @pacman82 suggested to use odbc2parquet if you want to go from ODBC to Parquet without the Arrow intermediary. To me this implies that it's also faster than going through arrow-odbc-py. In my benchmarks with comparable settings however, odbc2parquet is ~ 20% slower than going through arrow-odbc-py (with `read_concurrently()`) + `pyarrow.parquet`.

**Comment by jonashaag** [comment]
According to my profiling, 75% of the time is spent in the ODBC buffer -> RecordBatch conversion if you use `fetch_concurrently()`. But only 50% of time if you don't use it. Either this is a profiling artifact, or it means that the concurrent mode has significant overhead in the "Arrow thread". Also, it probably means that we could reasonably get up to a 1.5x speedup "just" by optimizing/parallelizing RecordBatch construction. Although I'm pretty sure that would require significant effort.

**Comment by jonashaag** [comment]
On another query arrow-odbc is much faster. Interesting.

**Comment by pacman82** [comment]
Faster is always better, but I am closing this issue. Not sure what the definition of done here would be.
