### ISSUE TITLE
Db2 VARCHAR column with empty string causes panic

### ISSUE THREAD

**Issue by rupurt** [pacman82/arrow-odbc-py#78]
This is a new issue based on comments in https://github.com/pacman82/arrow-odbc-py/issues/68?notification_referrer_id=NT_kwDOAApjVbE4Nzc5NTYwNDI4OjY4MDc4OQ#issuecomment-1910894395

Given a Db2 table with a column that has empty strings
And the column does not allow `NULL`'s
When I try to read the table into a `pyarrow` record batch
Then it should be mapped correctly
But it currently causes a panic

```shell
> evac odbc sql -c 'SELECT NUM FROM MYSCHEMA.MYTABLE' -v
DEBUG - ODBC Environment created.
DEBUG - SQLAllocHandle allocated connection (Dbc) handle '0x21976e0'
DEBUG - Database managment system name as reported by ODBC: DB2
DEBUG - ODBC driver reported for column 0. Relational type: Varchar { length: Some(20) }; Nullability: NoNulls; Name: 'NUM';
DEBUG - SQLColAttribute called with attribute 'ConciseType' for column '1' reported 12.
DEBUG - SQLColAttribute called with attribute 'DisplaySize' for column '1' reported 20.
DEBUG - Relational type of column 0: Varchar { length: Some(20) }
INFO - Column 'NUM'
Bytes used per row: 89
INFO - Total memory usage per row for single transit buffer: 89
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-odbc-6.1.0/src/reader/to_record_batch.rs:103:85:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Column 'NUM' is declared as non-nullable but contains null values")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

Table definition

```sql
CREATE TABLE "MYSCHEMA"."MYTABLE" (
		  "ID" INTEGER NOT NULL WITH DEFAULT  , 
		  "NUM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
		  "DTE" DATE NOT NULL WITH DEFAULT '9999-09-09'
) ;
```

**Comment by rupurt** [comment]
I added `polars` and used `pyodbc` with `polars.read_database(...)` and interestingly it seems to handle the string columns correctly on both LUW & Mainframe Db2.

I can confirm there are no `NULL`'s and no empty strings. They look like this `500 Sep 2023 - FWK3`

**Comment by pacman82** [comment]
What operating system are you executing `arrow-odbc` on? I would have expected the non-windows systems to emit the following warning:

> Ignoring indicators, because we expect the ODBC driver of your database to return garbage memory. We can not distiguish between empty strings and NULL. Everything is empty.

I am seeing that the name of your Database system is now `DB2`. In another instance I thought it to be `DB2/LINUX` did something change?

One reason we could see this error, is that I only activate the db2 workarounds if the system identifies as `DB2/LINUX`. Just using `DB2` avoids activating the workaround. It might very well be, that because of the broken indicators, some columns are now interpreted as NULL.

**Comment by rupurt** [comment]
I'm executing `arrow-odbc` on Linux/x86_64. But the error is only happening on the mainframe z/OS version of Db2. I don't seem to have the problem with the LUW version of Db2 if that helps.

Let me know what other kind of meta information you need and I can provide it as long as it doesn't leak any sensitive information.

**Comment by pacman82** [comment]
`arrow-odbc 2.1.5` has been released. It would activate the db2 workaround for any database which name start with db2. This should make it work on platforms besides linux

**Comment by pacman82** [comment]
Please tell me if this fixes your problem?

**Comment by keraion** [comment]
@pacman82 would it be possible to selectively enable or disable these quirks? While the libdb2.so driver has incorrect data with null fields, the libdb2o.so driver correctly indicates between empty strings and nulls.

**Comment by pacman82** [comment]
I guess it would. However I wonder, if we could auto-detect this? What database managment system name is logged if using `libdb2o.so`? As I am not familiar with db2, what is the difference between these?

**Comment by keraion** [comment]
The problem with querying the database for the dbms name is that it depends on the what the database returns, not the driver.

The issue with checking for "DB2", "DB2 Linux", "DB2 AIX" or any other combination is that it is reported by the database, not the driver.

The closest thing I was able to produce auto-detection was calling `SQLDrivers` and `SQLDataSources` pulling the data from the connection string looking for either a "Driver" or "Driver64" line.

This also led to an issue I found with `odbc_api::environment::Environment` and the `drivers` function only returning the first attribute, but I can post more about that later when I have a moment to type all that out.

**Comment by pacman82** [comment]
Thanks for the explanation. I did not realize it was solely the Database itself controlling that string. For me this means that I would actually walk back on auto detecting and provide users a way to specify these quirks themselves.

**Comment by pacman82** [comment]
> @pacman82 would it be possible to selectively enable or disable these quirks? While the libdb2.so driver has incorrect data with null fields, the libdb2o.so driver correctly indicates between empty strings and nulls.

`arrow-odbc 3.0.0` it allows you to set the parameter `driver_returns_memory_garbage_for_indicators` explicitly. It won't try to autodetect.

Best, Markus

**Comment by pacman82** [comment]
@rupurt Does setting this parameter explicitly to `True` solve this issue for you?

**Comment by keraion** [comment]
From what I can tell with libdb2.so, it is a 32-bit driver so it is trying to return everything with the 32-bit sizes, but with `odbc-api` correctly trying to read data in based on the system's "bitness" it's jumping over data and doubling up on types like `isize`.

Example query:
```sql
with t1 (col1) as (values 'hello', 'bonjour', '', NULL) select cast(col1 as varchar(50)) from t1;
```

libdb2.so:
```
DEBUG - ODBC driver reported for column 0. Relational type: Varchar { length: Some(50) }; Nullability: Nullable; Name: '1';
DEBUG - SQLColAttribute called with attribute 'ConciseType' for column '1' reported 12.
DEBUG - SQLColAttribute called with attribute 'DisplaySize' for column '1' reported 50.
DEBUG - Relational type of column 0: Varchar { length: Some(50) }
INFO - Column '1'
Bytes used per row: 209
INFO - Total memory usage per row for single transit buffer: 209
DEBUG - Indicator Size:30064771077
DEBUG - Indicator Size as 32-bit mask:5
DEBUG - Indicator Size:-4294967296
DEBUG - Indicator Size as 32-bit mask:0
thread '<unnamed>' panicked at ...
```

libdb2o.so:
```
DEBUG - ODBC driver reported for column 0. Relational type: Varchar { length: Some(50) }; Nullability: Nullable; Name: '1';
DEBUG - SQLColAttribute called with attribute 'ConciseType' for column '1' reported 12.
DEBUG - SQLColAttribute called with attribute 'DisplaySize' for column '1' reported 50.
DEBUG - Relational type of column 0: Varchar { length: Some(50) }
INFO - Column '1'
Bytes used per row: 209
INFO - Total memory usage per row for single transit buffer: 209
DEBUG - Indicator Size:5
DEBUG - Indicator Size as 32-bit mask:5
DEBUG - Indicator Size:7
DEBUG - Indicator Size as 32-bit mask:7
DEBUG - Indicator Size:0
DEBUG - Indicator Size as 32-bit mask:0
DEBUG - Indicator Size:-1
DEBUG - Indicator Size as 32-bit mask:4294967295
DEBUG - StringArray
[
  "hello",
  "bonjour",
  "",
  null,
]
```

**Comment by keraion** [comment]
More Docs on libdb2.so vs libdb2o.so:
https://www.ibm.com/docs/en/db2/11.5?topic=environment-setting-up-odbc-linux-unix
<html>
<body>
<ol class="steps bx--list--ordered--temporary" style="box-sizing: border-box; padding: 0px; border: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 1.5rem !important; margin-left: 1.25rem !important; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; line-height: 1.5rem !important; font-family: &quot;IBM Plex Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; list-style-position: initial; list-style-image: initial; list-style-type: decimal !important; letter-spacing: 0px !important; color: rgb(218, 215, 210); orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li class="step stepexpand bx--list__item" style="box-sizing: border-box; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0.25rem !important; border: 0px; margin: 0.25rem 0px 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: rgb(218, 215, 210);"><div class="itemgroup info" style="box-sizing: border-box; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.625rem; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline;"><div class="p" style="box-sizing: border-box; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.625rem; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline;"><ul class="bx--list--unordered bx--list--nested" style="box-sizing: border-box; padding: 0px; border: 0px; margin: 0px 0px 1rem 1rem; font-style: inherit; font-variant: inherit; font-weight: 400 !important; font-stretch: inherit; line-height: 1.5rem !important; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 1rem !important; vertical-align: baseline; list-style: none; letter-spacing: 0px !important;"><li class="bx--list__item" style="box-sizing: inherit; padding: 0px 0px 0px 0.25rem; border: 0px; margin: 0.25rem 0px 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: rgb(218, 215, 210); position: relative;"><div class="p" style="box-sizing: inherit; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.625rem; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline;">With the introduction of the 64-bit development environment, there have been a number of inconsistencies among vendors regarding the interpretation of the sizes of certain parameters. For example, the 64-bit Microsoft ODBC Driver Manager treats SQLHANDLE and SQLLEN as both 64-bits in length, whereas Data Direct Connect and open source ODBC driver managers treat SQLHANDLE as 64-bit, but SQLLEN as 32-bit. The developer must therefore pay careful attention to which version of the<span> </span><span class="keyword" style="box-sizing: inherit; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline;">Db2</span><span> </span>driver is required. Specify the appropriate<span> </span><span class="keyword" style="box-sizing: inherit; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline;">Db2</span><span> </span>driver in the data source stanza, according to the following information:<div class="bx--data-table-container" style="box-sizing: inherit; padding: 0.125rem 0px 0px; border: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 1.5rem !important; margin-left: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.625rem; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; position: relative; overflow: auto !important;">

|Type of application | Db2 driver to specify|
|-- | --|
|32-bit CLI | libdb2.*|
|32-bit ODBC Driver Manager | libdb2.*|
|64-bit CLI | libdb2.*|
|64-bit ODBC Driver Manager | libdb2o.* (db2o.o for AIX)|

</div><div class="note border-2 bx--inline-notification--info ibmdocs-note bx--inline-notification bx--inline-notification--low-contrast margin-top-1 margin-bottom-1" style="box-sizing: inherit; padding: 0px; border-width: 0px 0px 0px 3px; border-top-style: initial; border-right-style: initial; border-bottom-style: initial; border-left-style: solid; border-top-color: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: rgb(0, 63, 193); border-image: initial; margin-top: 1rem !important; margin-right: 0px; margin-bottom: 1rem !important; margin-left: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.625rem; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; width: 753.5px; max-width: 100%; position: relative; display: flex; min-width: 18rem; height: auto; min-height: 3rem; flex-wrap: nowrap; color: rgb(218, 215, 210); background: rgb(29, 32, 33);"><div class="bx--inline-notification__details" style="box-sizing: inherit; padding: 0px; border: 0px; margin: 0px 1rem; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.625rem; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; display: flex; -webkit-box-flex: 1; flex-grow: 1; overflow: auto hidden !important;"><svg focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" class="bx--inline-notification__icon" width="20" height="20" viewBox="0 0 32 32" aria-hidden="true" style="will-change: transform;"><path d="M16,2A14,14,0,1,0,30,16,14,14,0,0,0,16,2Zm0,5a1.5,1.5,0,1,1-1.5,1.5A1.5,1.5,0,0,1,16,7Zm4,17.12H12V21.88h2.88V15.12H13V12.88h4.13v9H20Z"></path></svg><div class="bx--inline-notification__text-wrapper" style="box-sizing: inherit; padding: 0.9375rem 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.625rem; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; display: flex; flex-wrap: wrap;"><div class="bx--inline-notification__subtitle" style="box-sizing: inherit; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; line-height: 1.5; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 1rem; vertical-align: baseline; letter-spacing: 0px; word-break: break-word;"><span class="notetitle ibm-bold ibm-textcolor-blue-50 background-blue bx--inline-notification__title ibm-padding-top-1 ibm-padding-bottom-1 padding-left-1 padding-right-1" style="box-sizing: inherit; padding: 1rem 0px; border: 0px; margin: 0px 0.25rem 0px 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; line-height: 1.5; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 1rem; vertical-align: baseline; letter-spacing: 0px; display: inline !important;">Note:</span><span> </span>The file extension of the<span> </span><span class="keyword" style="box-sizing: inherit; padding: 0px; border: 0px; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline;">Db2</span><span> </span>driver to specify depends on the operating system. The extensions are as follows:<ul class="bx--list--unordered bx--list--nested" style="box-sizing: inherit; padding: 0px; border: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px !important; margin-left: 1rem; font-style: inherit; font-variant: inherit; font-weight: 400 !important; font-stretch: inherit; line-height: inherit !important; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: inherit !important; vertical-align: baseline; list-style: none; letter-spacing: 0px !important;"><li class="bx--list__item" style="box-sizing: inherit; padding: 0px 0px 0px 0.25rem; border: 0px; margin: 0.25rem 0px 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: rgb(218, 215, 210); position: relative;">.a - AIX</li><li class="bx--list__item" style="box-sizing: inherit; padding: 0px 0px 0px 0.25rem; border: 0px; margin: 0.25rem 0px 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: rgb(218, 215, 210); position: relative;">.so - Linux, HP-IPF</li><li class="bx--list__item" style="box-sizing: inherit; padding: 0px 0px 0px 0.25rem; border: 0px; margin: 0.25rem 0px 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: rgb(218, 215, 210); position: relative;">.sl - HP-PA</li></ul></div></div></div></div></div></li></ul></div></div></li></ol><br class="Apple-interchange-newline">
</body>
</html>

https://www.ibm.com/docs/en/db2/11.5?topic=unix-sample-configurations
> The odbcinst.ini file is in the bin subdirectory of the unixODBC driver manager installation path. The Driver entry for each database section must point to the location where Db2 libraries are located.
There are multiple library files that are associated with Db2 ODBC driver. You must specify a Db2 library based on your application environment.
> - For a 32-bit unixODBC driver manager on the AIX® platform, you must specify the libdb2.a library for the Driver entry.
> - For a 32-bit unixODBC driver manager on the Linux and UNIX platform other than AIX, you must specify the libdb2.so library for the Driver entry.
> - For a 64-bit unixODBC driver manager on the AIX platform, you must specify the db2o.o library for the Driver entry.
> - For a 64-bit unixODBC driver manager on the Linux and UNIX platform other than AIX, you must specify the libdb2o.so library for the Driver entry.

**Comment by pacman82** [comment]
@keraion Thanks a lot for the insight! This explains a lot. I would argue though that this is not a matter of interpretation. IMHO the 64Bit Len is the right one and the others just messed up. @rupurt Would all your problems just go away if you used `libdb2o.so` as a driver?

I need to reflect a bit whether or not this allows me to come up with a fundamental better workaround. This can bite in so many ways.

**Comment by pacman82** [comment]
All good, we are all learning all the time.

**Comment by rupurt** [comment]
Haha for sure. I've learned so much about low level database driver performance. Priceless :smile: 

You've been amazing btw @pacman82. Really really appreciate it!
