### ISSUE TITLE
Add packet size connection attribute to read_arrow_batches_from_odbc & insert_into_table

### ISSUE THREAD

**Issue by rupurt** [pacman82/arrow-odbc-py#87]
The ODBC spec provides a connection attribute to control the size of the network packet. The attribute is called [`SQL_ATTR_PACKET_SIZE`](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetconnectattr-function?view=sql-server-ver16). Db2 doesn't support the spec version but has a custom attribute called [`SQL_ATTR_FET_BUF_SIZE`](https://www.ibm.com/docs/en/db2/11.5?topic=keywords-fet-buf-size) that achieves a similar result. The attribute must be set after the handle has been allocated but before the network connection is established.

The integer values of the attributes are:
- `SQL_ATTR_PACKET_SIZE` = 112
- `SQL_ATTR_FET_BUF` = 3001
 
I've received a ~2.5x increase in throughput using this attribute over a slow connection. 1.6 MB/s -> 4.2 MB/s

**Comment by pacman82** [comment]
`arrow-odbc 5.1.0` is released. It allows you to forward your suggestion for the packet to the ODBC driver. Support for this feature is fairly poor across drivers and most seem to ignore it though. Have fun.

I would like to avoid supporting driver specific features. Can it not be passed in the connection string?

**Comment by rupurt** [comment]
I couldn't figure out what the DSN attribute was called `FetBufSize/FET_BUF_SIZE` etc... didn't seem to work. There isn't much documentation on these attributes. However setting it on the connection via the C API did work.

I'm doing bulk ETL. So 2.5x was a huge improvement. I still feel like there's something going on with the network of my upstream database so I'm also going to try TCP window tuning in Linux to try and eek out some additional performance. I can download datasets from the mainframe over FTP between 15-20MB/s so 1-4MB/s over ODBC with pyodbc (slower in arrow-odbc/Turbodbc without this setting) seems odd.

**Comment by pacman82** [comment]
The packet size is done. I struggle to find out (even with the IBM documentation), what the fetch buffer is all about? Do you know what it does on the technical level, or is it just some parameter you changed and got a speed up.

So far I thought that the fetch buffer is the buffer ODBC stores the row set in it receives from the database. However, this would not make sense in this context, since one thing about `arrow-odbc` is, that it allocates these in the application code and passes them to the ODBC api in order for the driver to fill them.

Can you help my understanding here?

Best, Markus

**Comment by rupurt** [comment]
Haha, I definitely say it’s more of the latter… I was trying everything I could and this one made a noticeable impact. 

This was the only documentation page I could find on it https://www.ibm.com/docs/en/db2/11.5?topic=keywords-fet-buf-size

**Comment by pacman82** [comment]
Yeah, that's the one I found also. It is not clear to me what that buffer is precisely. Then it brought the speedup, did that application actually use ODBC bulk fetches there the buffers are supplied by the application, or did it fetch the data row for row?

**Comment by rupurt** [comment]
Yeah, it was faster up to ~100 for `FETCH_ROW_ARRAY_SIZE`. But then degrades pretty quickly as that batch size grows above 100

**Comment by pacman82** [comment]
Until I understand Fetch buffer size better, I will close this issue.
