### ISSUE TITLE
insert_into_table error: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near 'Audit'

### ISSUE THREAD

**Issue by martindut** [pacman82/arrow-odbc-py#91]
Hi.
I can succesfully read data from an Azure SQL Server database using read_arrow_batches_from_odbc.
If I use insert_into_table with the same connecting string, I get this error:
Error: Failure to execute the sql statement, sending the data to the database.
ODBC emitted an error calling 'SQLExecute':
State: 42000, Native error: 102, Message: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near 'Audit'.

`def dataframe_to_table(df):
    table = pa.Table.from_pandas(df)
    reader = pa.RecordBatchReader.from_batches(table.schema, table.to_batches())
    insert_into_table(
        connection_string=connection_string,
        chunk_size=1000,
        table="tmp_test",
        reader=reader,
    )
dataframe_to_table(to_format_db)`

Is there a way to debug this to find out if the error is on my side?

**Comment by martindut** [comment]
Apologies, my mistake, I had a badly formatted column name.

**Comment by pacman82** [comment]
np, have fun with `arrow-odbc`.

**Comment by pacman82** [comment]
Maybe there is something for me to do here though. An error message about an ill formatted SQL statement is not helpful, if the statement is not provided by the user.

**Comment by pacman82** [comment]
May I ask what the syntax error had been?

**Comment by martindut** [comment]
Sorry, I did not see your previous question. The dataframe had a column named "Audit-->", so the error just said Incorrect syntax near 'Audit', which would have made sense if I knew there was such a column.

**Comment by pacman82** [comment]
hi, the newest version would wrap the `Audit-->` in double quotes `"Audit-->"` which should make it a valid column name in the newest standards. My hope is, that the error you would have gotten than, would be something like, no column named `Audit-->` instead. Rather than invalid syntax. If you want, you can give the newest version a spin, and tell me if that would have worked for you and with your database.
