### ISSUE TITLE
Tinyint Mapping

### ISSUE THREAD

**Issue by aersam** [pacman82/arrow-odbc-py#94]
In MS SQL Server, tinyint is an unsigned int. It should be mapped to uint8 therefore, I think

https://learn.microsoft.com/en-us/sql/t-sql/data-types/int-bigint-smallint-and-tinyint-transact-sql?view=sql-server-ver16

**Comment by aersam** [comment]
Other Systems like Spark have signed tinyint's, so maybe needs some differentiation

**Comment by pacman82** [comment]
According to <https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/sql-data-types?view=sql-server-ver16> tinyint can be both. Need to think about his.

**Comment by aersam** [comment]
Reading only for now

**Comment by aersam** [comment]
Well, is there metadata about the signed/unsigned thing?
